// Seed data for sandbox/demo mode — mimics real Supabase tables

export const seedCases: any[] = [
  {
    id: "case-001",
    user_id: "demo-user",
    name: "State v. Martinez",
    case_type: "Criminal Defense",
    client_name: "Carlos Martinez",
    status: "active",
    representation: "defense",
    case_theory: "Police officers fabricated evidence of drug possession to retaliate against Martinez for his First Amendment-protected complaints about police misconduct. The fabricated evidence led to wrongful arrest and 6 months of pretrial detention.",
    key_issues: [
      "Credibility of arresting officers under Internal Affairs investigation",
      "Chain of custody gaps in evidence log (47-minute discrepancy)",
      "Missing body cam footage from 12-minute window during arrest",
      "Conflicting witness statements about location of alleged drugs",
    ],
    winning_factors: [
      "Internal Affairs complaint filed 2 weeks before arrest",
      "Two independent witnesses contradict officer testimony",
      "Crime lab analyst willing to testify about evidence irregularities",
      "Officer had prior suspension for evidence handling violation",
    ],
    next_deadline: "2026-07-15",
    notes: "Priority case — client in pretrial detention 6 months. Judge Patterson presiding.",
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-06-20T14:30:00Z",
  },
  {
    id: "case-002",
    user_id: "demo-user",
    name: "Estate of Johnson v. Mercy Hospital",
    case_type: "Medical Malpractice",
    client_name: "Johnson Estate (Sarah Johnson, Executrix)",
    status: "active",
    representation: "plaintiff",
    case_theory: "Hospital failed to properly monitor post-surgical patient, leading to undetected internal hemorrhage and death. Deviation from standard of care in post-operative monitoring protocols.",
    key_issues: [
      "Nurse staffing ratios below state minimum on night of incident",
      "Vital signs not recorded for 4-hour period post-surgery",
      "Attending physician left hospital without sign-off to relief",
      "Hospital policy required ICU transfer that was not initiated",
    ],
    winning_factors: [
      "Expert witness: board-certified surgeon willing to testify",
      "Hospital's own policy manual supports our position",
      "Damages clearly quantified (lost wages, funeral, loss of consortium)",
    ],
    next_deadline: "2026-08-01",
    notes: "Mediation scheduled for July 20. Demand letter sent.",
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-06-18T11:00:00Z",
  },
  {
    id: "case-003",
    user_id: "demo-user",
    name: "Thompson v. City Police Dept",
    case_type: "Civil Rights",
    client_name: "Michael Thompson",
    status: "active",
    representation: "plaintiff",
    case_theory: "Client was not driving at time of DUI stop. Passenger switched seats after vehicle was pulled over. Field sobriety tests administered to wrong person.",
    key_issues: [
      "Dash cam video shows passenger exiting driver side",
      "Officer failed to confirm who was driving before arrest",
      "Body cam shows client in passenger seat at time of stop",
    ],
    winning_factors: [
      "Clear video evidence exonerating client",
      "Officer's report contains factual errors about seating",
      "Passenger willing to testify she was driving",
    ],
    next_deadline: "2026-07-30",
    notes: "Motion to suppress filed. Hearing set for July 10.",
    created_at: "2026-03-10T08:00:00Z",
    updated_at: "2026-06-25T16:00:00Z",
  },
  {
    id: "case-004",
    user_id: "demo-user",
    name: "Rodriguez v. TechCorp Inc",
    case_type: "Employment Law",
    client_name: "Maria Rodriguez",
    status: "active",
    representation: "plaintiff",
    case_theory: "Employee terminated after reporting sexual harassment to HR. Termination pretextual - performance reviews were positive until complaint was filed.",
    key_issues: [
      "Timeline: termination 3 weeks after HR complaint",
      "Performance reviews positive for 2 years before complaint",
      "No prior disciplinary actions on record",
      "HR failed to investigate complaint per company policy",
    ],
    winning_factors: [
      "Documented HR complaint with timestamp",
      "Emails showing positive performance feedback",
      "Coworker witnesses to harassment behavior",
    ],
    next_deadline: "2026-09-15",
    notes: "EEOC charge filed. Investigative conference scheduled.",
    created_at: "2026-04-05T12:00:00Z",
    updated_at: "2026-06-22T09:30:00Z",
  },
];

export const seedDocuments: any[] = [
  {
    id: "doc-001", case_id: "case-001", user_id: "demo-user",
    name: "Police Report - Arrest Report", file_url: null, file_type: "pdf", file_size: 245678,
    bates_number: "PR-001",
    summary: "Arrest report filed by Officer Smith. Reports discovery of controlled substance in vehicle glove compartment. Notably missing details about initial traffic stop reason.",
    key_facts: ["Traffic stop initiated at 11:47 PM", "Officer claims drugs found in glove compartment", "No mention of body cam activation time"],
    favorable_findings: ["Report does not mention reason for initial traffic stop", "Arresting officer's signature differs from other reports"],
    adverse_findings: ["Officer claims direct observation of drugs"],
    action_items: ["Subpoena body cam footage", "Request Internal Affairs records"],
    ai_analyzed: true,
    ocr_text: "ARREST REPORT\n\nDate: 2025-12-15\nTime: 11:47 PM\nOfficer: J. Smith, Badge #4471\n\nSubject: Carlos Martinez\n\nCharges: Possession of Controlled Substance (H&S Code 11377(a))\n\nNarrative: At approximately 11:47 PM, I observed vehicle proceeding northbound on I-5. Vehicle was stopped and driver identified as Carlos Martinez. During search of vehicle, I discovered a bag containing suspected controlled substance in the glove compartment...",
    ocr_processed_at: "2026-01-20T10:00:00Z", ocr_provider: "azure", extracted_tables: null,
    created_at: "2026-01-16T09:00:00Z", updated_at: "2026-01-20T10:00:00Z",
  },
  {
    id: "doc-002", case_id: "case-001", user_id: "demo-user",
    name: "Body Camera Footage Log", file_url: null, file_type: "pdf", file_size: 89234,
    bates_number: "BC-001",
    summary: "Body cam log showing a 12-minute gap in footage during the arrest. Officer Smith's camera was reportedly 'malfunctioning' during the critical search period.",
    key_facts: ["12-minute gap in body cam footage (11:35-11:47 PM)", "Camera logged as 'malfunctioning'", "Footage resumes after arrest was already made"],
    favorable_findings: ["Gap covers exact period of alleged drug discovery", "No maintenance record for camera malfunction"],
    adverse_findings: [],
    action_items: ["Request camera maintenance records", "Subpoena IT logs for body cam system"],
    ai_analyzed: true,
    ocr_text: "BODY CAMERA FOOTAGE LOG\n\nOfficer: J. Smith, Badge #4471\nDate: 2025-12-15\nCamera ID: BC-4471-A\n\n11:20 PM - Camera activated (routine patrol)\n11:35 PM - Signal lost (malfunction reported)\n11:47 PM - Camera signal restored\n11:48 PM - Arrest in progress (footage resumes)\n\nNote: 12-minute signal gap attributed to device malfunction. No maintenance ticket filed.",
    ocr_processed_at: "2026-01-20T10:05:00Z", ocr_provider: "azure", extracted_tables: null,
    created_at: "2026-01-16T09:05:00Z", updated_at: "2026-01-20T10:05:00Z",
  },
  {
    id: "doc-003", case_id: "case-001", user_id: "demo-user",
    name: "Witness Statement - Maria Gonzalez", file_url: null, file_type: "pdf", file_size: 56123,
    bates_number: "WS-001",
    summary: "Independent witness statement contradicting officer's account. Witness states she saw passenger, not Martinez, exit driver side of vehicle.",
    key_facts: ["Witness observed traffic stop from adjacent parking lot", "Witness states passenger exited driver side", "Witness did not see any search of vehicle"],
    favorable_findings: ["Independent witness with no connection to defendant", "Corroborates Martinez's account of events"],
    adverse_findings: ["Witness was approximately 50 feet away", "Visibility limited by street lighting"],
    action_items: ["Prepare witness for deposition", "Obtain witness's phone records to confirm presence"],
    ai_analyzed: true,
    ocr_text: "WITNESS STATEMENT\n\nName: Maria Gonzalez\nDate of Statement: 2025-12-16\nLocation: Starbucks parking lot, I-5 exit 42\n\nI was sitting in my car in the Starbucks parking lot on the night of December 15th. I saw a police car pull over a sedan on the freeway off-ramp. I saw the passenger door open and a woman get out from the passenger side. The officer spoke to the driver. I did not see anyone search the car...",
    ocr_processed_at: "2026-01-20T10:10:00Z", ocr_provider: "azure", extracted_tables: null,
    created_at: "2026-01-16T09:10:00Z", updated_at: "2026-01-20T10:10:00Z",
  },
  {
    id: "doc-004", case_id: "case-001", user_id: "demo-user",
    name: "Internal Affairs Complaint", file_url: null, file_type: "pdf", file_size: 178456,
    bates_number: "IA-001",
    summary: "Internal Affairs complaint filed by Martinez 2 weeks before his arrest. Complaint alleges Officer Smith used excessive force in a prior encounter.",
    key_facts: ["Complaint filed 2025-12-01", "Alleges excessive force by Officer Smith", "Complaint pending investigation at time of arrest"],
    favorable_findings: ["Establishes motive for retaliatory arrest", "Shows prior history of complaints against officer"],
    adverse_findings: [],
    action_items: ["Obtain IA investigation file", "Subpoena IA investigator testimony"],
    ai_analyzed: true,
    ocr_text: "INTERNAL AFFAIRS COMPLAINT\n\nComplaint Number: IA-2025-0892\nDate Filed: December 1, 2025\nComplainant: Carlos Martinez\nSubject Officer: J. Smith, Badge #4471\n\nNature of Complaint: Excessive force, verbal abuse, and intimidation during traffic stop on November 28, 2025.\n\nSummary: Complainant alleges that Officer Smith used excessive force during a routine traffic stop...",
    ocr_processed_at: "2026-01-20T10:15:00Z", ocr_provider: "azure", extracted_tables: null,
    created_at: "2026-01-16T09:15:00Z", updated_at: "2026-01-20T10:15:00Z",
  },
  {
    id: "doc-005", case_id: "case-002", user_id: "demo-user",
    name: "Post-Op Nursing Notes", file_url: null, file_type: "pdf", file_size: 234567,
    bates_number: "MED-001",
    summary: "Post-operative nursing notes showing 4-hour gap in vital signs monitoring. Patient stable at 8 PM but found unresponsive at midnight.",
    key_facts: ["4-hour gap in vital signs (8 PM to midnight)", "Last recorded BP: 110/70 (stable)", "Patient found unresponsive at 12:04 AM", "Nurse-to-patient ratio was 1:8 (state minimum is 1:4)"],
    favorable_findings: ["Gap in monitoring violates hospital policy", "Staffing levels below state minimum"],
    adverse_findings: ["Patient had underlying cardiovascular condition"],
    action_items: ["Obtain hospital staffing records", "Subpoena nurse who was on duty"],
    ai_analyzed: true,
    ocr_text: "POST-OPERATIVE NURSING NOTES\nPatient: Robert Johnson\nDOB: 03/15/1958\nMRN: 7782341\nSurgery: Laparoscopic cholecystectomy\nPost-Op Day: 0\n\n2000 (8:00 PM): Patient resting comfortably. Vitals: BP 110/70, HR 72, RR 16, Temp 98.6F.\n\n[GAP IN DOCUMENTATION - No entries between 8:00 PM and 12:04 AM]\n\n0004 (12:04 AM): Patient found unresponsive during rounds. Code Blue called.\n\nNote: Staffing level on night shift: 1 RN for 8 patients. (State minimum: 1 RN per 4 patients.)",
    ocr_processed_at: "2026-02-05T10:00:00Z", ocr_provider: "azure", extracted_tables: null,
    created_at: "2026-02-02T09:00:00Z", updated_at: "2026-02-05T10:00:00Z",
  },
  {
    id: "doc-006", case_id: "case-002", user_id: "demo-user",
    name: "Hospital Policy Manual - Post-Op Care", file_url: null, file_type: "pdf", file_size: 345678,
    bates_number: "POL-001",
    summary: "Hospital policy manual requiring vital signs every 2 hours post-surgery and ICU transfer for patients with cardiovascular history.",
    key_facts: ["Policy requires vitals every 2 hours post-op", "ICU transfer required for patients with CV history", "Patient had documented cardiovascular condition"],
    favorable_findings: ["Hospital violated its own policy", "ICU transfer could have prevented death"],
    adverse_findings: [],
    action_items: ["Obtain full policy manual", "Identify who made staffing decision"],
    ai_analyzed: true,
    ocr_text: "MERCY HOSPITAL POLICY MANUAL\nSection 4.7: Post-Operative Monitoring Protocol\n\n4.7.1 All post-operative patients shall have vital signs recorded every 2 hours for the first 24 hours.\n\n4.7.2 Patients with documented cardiovascular history shall be transferred to ICU for post-operative monitoring.\n\n4.7.3 Minimum staffing ratio for post-operative floor: 1 RN per 4 patients.",
    ocr_processed_at: "2026-02-05T10:05:00Z", ocr_provider: "azure", extracted_tables: null,
    created_at: "2026-02-02T09:05:00Z", updated_at: "2026-02-05T10:05:00Z",
  },
];

export const seedTimelineEvents: any[] = [
  { id: "te-001", case_id: "case-001", user_id: "demo-user", title: "Initial Traffic Stop", date: "2025-12-15T23:47:00Z", description: "Officer Smith initiates traffic stop on I-5", document_id: "doc-001", created_at: "2026-01-20T10:00:00Z" },
  { id: "te-002", case_id: "case-001", user_id: "demo-user", title: "Body Cam Gap", date: "2025-12-15T23:35:00Z", description: "12-minute gap in body cam footage begins", document_id: "doc-002", created_at: "2026-01-20T10:05:00Z" },
  { id: "te-003", case_id: "case-001", user_id: "demo-user", title: "Witness Observation", date: "2025-12-15T23:50:00Z", description: "Maria Gonzalez observes traffic stop from parking lot", document_id: "doc-003", created_at: "2026-01-20T10:10:00Z" },
  { id: "te-004", case_id: "case-001", user_id: "demo-user", title: "IA Complaint Filed", date: "2025-12-01T00:00:00Z", description: "Martinez files complaint against Officer Smith with Internal Affairs", document_id: "doc-004", created_at: "2026-01-20T10:15:00Z" },
  { id: "te-005", case_id: "case-002", user_id: "demo-user", title: "Post-Op Monitoring Begins", date: "2026-01-20T20:00:00Z", description: "Patient transferred to post-op floor after surgery", document_id: "doc-005", created_at: "2026-02-05T10:00:00Z" },
  { id: "te-006", case_id: "case-002", user_id: "demo-user", title: "Patient Found Unresponsive", date: "2026-01-21T00:04:00Z", description: "Patient found unresponsive during nurse rounds - 4 hour monitoring gap", document_id: "doc-005", created_at: "2026-02-05T10:05:00Z" },
];
